import type {NextPage} from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../components/l4_template/Header";
import Footer from "../components/l4_template/Footer";
import Subtitle from "../components/l1_atoms/Subtitle";
import ImageContent from "../components/l2_molecules/ImageContent";
import GridMatterOfInterest from "../components/l2_molecules/GridMatterOfInterest";

const Home: NextPage = () => {
  const subtitleLinks = [
    {
      subtitle: "About",
      link: "about",
    },
    {
      subtitle: "Bicycle",
      link: "bicycle",
    },
  ];
  const matterOfInterestPropsAry = [
    {
      imageSetWH: {
        imageSrc: "/assets/bicycle1.jpg",
        imageAlt: "bicycle1",
        width: 640,
        height: 424,
      },
      title: "自転車1",
      message: "hogehoge1",
    },
    {
      imageSetWH: {
        imageSrc: "/assets/bicycle2.jpg",
        imageAlt: "bicycle2",
        width: 640,
        height: 424,
      },
      title: "自転車2",
      message: "hogehoge2",
    },
    {
      imageSetWH: {
        imageSrc: "/assets/bicycle3.jpg",
        imageAlt: "bicycle3",
        width: 640,
        height: 424,
      },
      title: "自転車3",
      message: "hogehoge3",
    },
    // {
    //   imageSetWH: {
    //     imageSrc: "/assets/bicycle3.jpg",
    //     imageAlt: "bicycle4",
    //     width: 640,
    //     height: 424,
    //   },
    //   title: "自転車4",
    //   message: "hogehoge4",
    // },
  ];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.ico" />
      </Head>
      <Header title="Profile" subtitleLinks={subtitleLinks} />
      <div className="relative h-160 max-h-full">
        <Image
          src="/assets/mainvisual.jpg"
          alt="Cycle Image"
          width={1980}
          height={640}
          loading={"lazy"}
          layout="fill"
          objectFit="cover"
        />
      </div>
      <div className="flex flex-col items-center">
        <ImageContent
          subtitleLink={{
            subtitle: "About",
            link: "about",
          }}
          imageSet={{
            imageSrc: "/assets/about.jpg",
            imageAlt: "about Image",
            size: 96,
          }}
          label="hoge fuga"
          message={`Lorem ipsum dolor sit, amet consectetur adipisicing elit.
            Exercitationem vero illum dolor, explicabo mollitia nam dolores,
            recusandae officia aliquam eum molestiae laudantium laborum
            voluptatibus ipsa perferendis dolorem minima architecto facilis?`}
        />
        <Subtitle
          subtitle={subtitleLinks[1].subtitle}
          link={subtitleLinks[1].link}
        />
        <div className="m-5 w-4/5">
          <GridMatterOfInterest
            matterOfInterestPropsAry={matterOfInterestPropsAry}
          />
        </div>
      </div>
      <Footer name="Yutaka Fujii" />
    </div>
  );
};

export default Home;
